# Generated by Django 3.2.9 on 2021-11-07 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PL', 'Výsadba'), ('TR', 'Přesazování'), ('VA', 'Očkování'), ('GR', 'Roubování'), ('PC', 'Ochrana proti škůdcům'), ('HA', 'Sklizeň'), ('FE', 'Hnojení'), ('RE', 'Zmlazování'), ('PR', 'Stříhání')], max_length=2, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeOfEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('species', models.CharField(choices=[('TR', 'Strom'), ('BU', 'Keř'), ('HR', 'Bylina')], max_length=2, unique=True)),
                ('type', models.CharField(choices=[('FR', 'Ovoce'), ('VE', 'Zelenina'), ('DE', 'Okrasné')], max_length=2, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='zahradka_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=512)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to='zahradka_app.plant')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='zahradka_app.timeofevent'),
        ),
    ]
