# Generated by Django 3.2.9 on 2021-12-04 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import zahradka_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PL', 'Výsadba'), ('TR', 'Přesazování'), ('VA', 'Očkování'), ('GR', 'Roubování'), ('PC', 'Ochrana proti škůdcům'), ('HA', 'Sklizeň'), ('FE', 'Hnojení'), ('RE', 'Zmlazování'), ('PR', 'Stříhání'), ('OT', 'Iné')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('address', models.CharField(max_length=512)),
                ('garden_image', models.ImageField(blank=True, null=True, upload_to=zahradka_app.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('membership_type', models.CharField(choices=[('PL', 'plus'), ('FR', 'základní')], default='FR', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=999)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('species', models.CharField(choices=[('TR', 'Strom'), ('BU', 'Keř'), ('HR', 'Bylina')], max_length=2)),
                ('type', models.CharField(choices=[('FR', 'Ovoce'), ('VE', 'Zelenina'), ('DE', 'Okrasné'), ('OT', 'Ostatní')], max_length=2)),
                ('plant_image', models.ImageField(blank=True, max_length=20, null=True, upload_to='static/plant_photos/')),
                ('place', models.CharField(default='', max_length=256)),
                ('soil', models.CharField(default='', max_length=256)),
                ('other', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_membership', to='zahradka_app.membership')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeOfEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='zahradka_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('user_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='zahradka_app.usermembership')),
            ],
        ),
        migrations.CreateModel(
            name='GardenPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zahradka_app.garden')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zahradka_app.plant')),
            ],
        ),
        migrations.AddField(
            model_name='garden',
            name='plant',
            field=models.ManyToManyField(blank=True, related_name='gardens', through='zahradka_app.GardenPlant', to='zahradka_app.Plant'),
        ),
        migrations.AddField(
            model_name='garden',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='zahradka_app.plant'),
        ),
    ]
