# Generated by Django 3.2.9 on 2021-12-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahradka_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='other',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='static/plant_photos/'),
        ),
    ]
