# Generated by Django 3.2.9 on 2021-11-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahradka_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('PLANTING', 'Výsadba'), ('TRANSPLANTING', 'Přesazování'), ('VACCINATION', 'Očkování'), ('GRAFTING', 'Roubování'), ('PEST_CONTROL', 'Ochrana proti škůdcům'), ('HARVESTING', 'Sklizeň'), ('FERTILISATION', 'Hnojení'), ('REJUVENATION', 'Zmlazování'), ('PRUNING', 'Stříhání')], max_length=20),
        ),
    ]
