# Generated by Django 3.2.9 on 2021-11-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahradka_app', '0002_garden_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plant_image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
