# Generated by Django 3.2.9 on 2021-12-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahradka_app', '0002_auto_20211204_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(choices=[('PL', 'výsadba'), ('TR', 'přesazování'), ('VA', 'očkování'), ('GR', 'roubování'), ('PC', 'ošetření'), ('HA', 'sklizeň'), ('FE', 'hnojení'), ('RE', 'zmlazování'), ('PR', 'stříhání'), ('OT', 'jiné')], max_length=20),
        ),
    ]
