# Generated by Django 3.2.9 on 2021-11-07 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zahradka_app', '0002_auto_20211107_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='zahradka_app.plant'),
        ),
        migrations.AddField(
            model_name='timeofevent',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='zahradka_app.event'),
        ),
        migrations.RemoveField(
            model_name='garden',
            name='plant',
        ),
        migrations.AddField(
            model_name='garden',
            name='plant',
            field=models.ManyToManyField(related_name='gardens', to='zahradka_app.Plant'),
        ),
    ]
