# Generated by Django 3.2.9 on 2021-11-07 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zahradka_app', '0003_auto_20211107_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='zahradka_app.plant'),
        ),
        migrations.AlterField(
            model_name='timeofevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='zahradka_app.event'),
        ),
    ]
