# Generated by Django 3.2.9 on 2021-11-21 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zahradka_app', '0003_rename_type_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('membership_type', models.CharField(choices=[('PL', 'plus'), ('FR', 'základní')], default='FR', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=999)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(choices=[('PL', 'Výsadba'), ('TR', 'Přesazování'), ('VA', 'Očkování'), ('GR', 'Roubování'), ('PC', 'Ochrana proti škůdcům'), ('HA', 'Sklizeň'), ('FE', 'Hnojení'), ('RE', 'Zmlazování'), ('PR', 'Stříhání')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_membership', to='zahradka_app.membership')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('user_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='zahradka_app.usermembership')),
            ],
        ),
    ]
