# Generated by Django 3.2.9 on 2021-11-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahradka_app', '0004_auto_20211121_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='garden_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
