# Generated by Django 3.2.9 on 2021-11-28 09:14

from django.db import migrations, models
import zahradka_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('zahradka_app', '0005_garden_garden_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='garden_image',
            field=models.ImageField(blank=True, null=True, upload_to=zahradka_app.models.user_directory_path),
        ),
    ]
