# Generated by Django 3.2.9 on 2021-11-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahradka_app', '0006_alter_garden_garden_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='plant',
            field=models.ManyToManyField(blank=True, related_name='gardens', through='zahradka_app.GardenPlant', to='zahradka_app.Plant'),
        ),
    ]
