# Generated by Django 3.2.9 on 2021-12-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahradka_app', '0007_alter_garden_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='other',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(choices=[('PL', 'Výsadba'), ('TR', 'Přesazování'), ('VA', 'Očkování'), ('GR', 'Roubování'), ('PC', 'Ochrana proti škůdcům'), ('HA', 'Sklizeň'), ('FE', 'Hnojení'), ('RE', 'Zmlazování'), ('PR', 'Stříhání'), ('OT', 'Iné')], max_length=20),
        ),
    ]
