# Generated by Django 3.2.9 on 2021-12-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahradka_app', '0008_auto_20211202_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='place',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='plant',
            name='soil',
            field=models.CharField(default='', max_length=256),
        ),
    ]
