# Generated by Django 3.2.9 on 2021-12-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahradka_app', '0009_auto_20211202_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='type',
            field=models.CharField(choices=[('FR', 'Ovoce'), ('VE', 'Zelenina'), ('DE', 'Okrasné'), ('OT', 'Ostatní')], max_length=2),
        ),
    ]
